In [1]:
# Core Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from scipy import stats
from scipy.stats import randint, uniform

## IMPORT & EXPLORE

In [45]:
flo_products = pd.read_csv(r"C:\Users\User\Downloads\flo\flo_products.csv")
all_products_combined = pd.read_csv(r"C:\Users\User\Downloads\flip_data_vlm_ext\all_products_combined.csv")
all_products_combinedv1 = pd.read_csv(r"C:\Users\User\Downloads\flip_data_vlm\flip_data_vlm\all_products_combined.csv")

In [5]:
flo_products.sample(10)

,title,url,image
46,Мужской Кроссовки Синий,https://www.flo.com.kz/ru/product/kinetix-int1...,images/23702c378174_e685359c.jpg
410,Мужской Кроссовки Зеленый,https://www.flo.com.kz/ru/product/adidas-barre...,images/cb527f94ced4_cec2a5b3.jpg
1691,Мужской Сандалии Черный,https://www.flo.com.kz/ru/product/flexall-int1...,images/eb66454224b8_1fba044a.jpg
1394,Женский Черный,https://www.flo.com.kz/ru/product/polaris-int1...,images/96a2025559a3_890c6645.jpg
2006,Женский Кроссовки Серый,https://www.flo.com.kz/ru/product/reebok-club-...,images/cb582d604f96_63a50206.jpg
3249,Мужской Серый,https://www.flo.com.kz/ru/product/kinetix-ml-i...,images/b23e3b6f53ad_f1417cb2.jpg
893,Мужской Кроссовки Белый,https://www.flo.com.kz/ru/product/lumberjack-l...,images/2e64a8c1e6e8_2566e96f.jpg
1117,Мужской Тапочки Черный,https://www.flo.com.kz/ru/product/polaris-int1...,images/74ab2a6617f5_d2367b73.jpg
145,Кроссовки Белый,https://www.flo.com.kz/ru/product/nike-court-b...,images/6bdf6e58a04e_bc2e786a.jpg
220,Кроссовки Черный,https://www.flo.com.kz/ru/product/kinetix-hall...,images/4282d80193a8_26a075a7.jpg

In [6]:
all_products_combined.sample(10)

,title,local_image_path,product_url
3863,Коммутатор TL-SG1048,/root/flip/data/category_1/images/Коммутатор_T...,https://www.flip.kz/catalog?prod=1914354
6573,"Трусы-макси женские комплект, антрацит, 52RU/2XL",/root/flip/data/category_2/images/Трусы_макси_...,https://www.flip.kz/catalog?prod=3843289
3983,Коммутатор LS1005,/root/flip/data/category_1/images/Коммутатор_L...,https://www.flip.kz/catalog?prod=2006656
2871,Wi-Fi точка доступа EAP265 HD,/root/flip/data/category_1/images/Wi_Fi_точка_...,https://www.flip.kz/catalog?prod=2257239
5092,Набор проводной MF410,/root/flip/data/category_1/images/Набор_провод...,https://www.flip.kz/catalog?prod=2121487
1729,"Коврик игровой Bloody B-072, 27.5×22.5×0.4 см",/root/flip/data/category_1/images/Коврик_игров...,https://www.flip.kz/catalog?prod=1565220
6115,"Пиджак женский, черный, 46RU - 50RU",/root/flip/data/category_2/images/Пиджак_женск...,https://www.flip.kz/catalog?prod=3122343
1849,Коммутатор USW-24-POE-EU,/root/flip/data/category_1/images/Коммутатор_U...,https://www.flip.kz/catalog?prod=2734834
3056,"SSD накопитель SA400S37, 240 ГБ",/root/flip/data/category_1/images/SSD_накопите...,https://www.flip.kz/catalog?prod=2024110
3320,Набор фотобумаги матовой двухсторонней,/root/flip/data/category_1/images/Набор_фотобу...,https://www.flip.kz/catalog?prod=4773437

In [10]:
all_products_combinedv1.sample(10)

,title,local_image_path,product_url
5435,"Термокружка с компасом «Boss», черный",/root/flip/data/category_1/images/Термокружка_...,https://www.flip.kz/catalog?prod=4681296
8018,"Средство для смягчения воды, 750 мл",/root/flip/data/category_2/images/Средство_для...,https://www.flip.kz/catalog?prod=2391795
11556,Свеча-цифра «1»,/root/flip/data/category_2/images/Свеча_цифра_...,https://www.flip.kz/catalog?prod=4607113
4022,Топор мясорубный,/root/flip/data/category_1/images/Топор_мясору...,https://www.flip.kz/catalog?prod=2347626
12626,Бутербродница КТ-1609,/root/flip/data/category_3/images/Бутербродниц...,https://www.flip.kz/catalog?prod=1627561
3522,"Кроссовки для девочек, розовый, 30RU",/root/flip/data/category_1/images/Кроссовки_дл...,https://www.flip.kz/catalog?prod=3554855
6578,Салфетки бумажные мягкие,/root/flip/data/category_2/images/Салфетки_бум...,https://www.flip.kz/catalog?prod=3381590
11796,Порошок мыльный хозяйственный «Универсальный»,/root/flip/data/category_2/images/Порошок_мыль...,https://www.flip.kz/catalog?prod=3681624
1182,Набор стаканов бумажных «Гербы Хогвартса»,/root/flip/data/category_1/images/Набор_стакан...,https://www.flip.kz/catalog?prod=3345104
6982,Набор стаканов одноразовых,/root/flip/data/category_2/images/Набор_стакан...,https://www.flip.kz/catalog?prod=2187660

## CLEAN & PREPARE

In [7]:
all_products_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6616 entries, 0 to 6615
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             6616 non-null   object
 1   local_image_path  6616 non-null   object
 2   product_url       6616 non-null   object
dtypes: object(3)
memory usage: 155.2+ KB

In [8]:
flo_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3752 entries, 0 to 3751
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   3752 non-null   object
 1   url     3752 non-null   object
 2   image   3752 non-null   object
dtypes: object(3)
memory usage: 88.1+ KB

In [46]:
flo_products = flo_products.rename( columns = {"url" : "product_url", "image" : "local_image_path"} )

In [47]:
all_products_combined["local_image_path"] = (
    all_products_combined["local_image_path"]
    .str.replace("/root/flip/data/category_1/", "/root/flip/data/category_4/", regex=False)
    .str.replace("/root/flip/data/category_2/", "/root/flip/data/category_5/", regex=False)
)

In [48]:
flo_products["local_image_path"] = flo_products["local_image_path"].str.replace( "images/", "/flo_images/", regex = False )

In [49]:
all_products_combined_ext = pd.concat([all_products_combined, all_products_combinedv1, flo_products])

In [50]:
all_products_combined_ext.duplicated().sum()

0

In [51]:
all_products_combined_ext.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28448 entries, 0 to 3751
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             28448 non-null  object
 1   local_image_path  28447 non-null  object
 2   product_url       28448 non-null  object
dtypes: object(3)
memory usage: 889.0+ KB

In [52]:
all_products_combined_ext.sample(20)

,title,local_image_path,product_url
8360,Набор салфеток бумажных «Смола серая»,/root/flip/data/category_2/images/Набор_салфет...,https://www.flip.kz/catalog?prod=2785399
3732,Ремешок для браслета Xiaomi Smart Band 9,/root/flip/data/category_4/images/Ремешок_для_...,https://www.flip.kz/catalog?prod=3885522
937,Беспроводные наушники внутриканальные,/root/flip/data/category_4/images/Беспроводные...,https://www.flip.kz/catalog?prod=4673624
3002,"Шейкер электрический, молочный",/root/flip/data/category_1/images/Шейкер_элект...,https://www.flip.kz/catalog?prod=4608737
4551,"Мяч «Ёжик» (8,5 см)",/root/flip/data/category_1/images/Мяч_Ёжик_85_...,https://www.flip.kz/catalog?prod=878739
5840,Нож многофункциональный 11 в 1,/root/flip/data/category_1/images/Нож_многофун...,https://www.flip.kz/catalog?prod=4689014
7426,"Полотенце махровое «Graphics», 100×150 см",/root/flip/data/category_2/images/Полотенце_ма...,https://www.flip.kz/catalog?prod=2114344
1532,Мужской Кроссовки Синий,/flo_images/e07afe8573d9_9c0000e3.jpg,https://www.flo.com.kz/ru/product/kinetix-int-...
2157,Bluetooth наушники Redmi Buds 3,/root/flip/data/category_4/images/Bluetooth_на...,https://www.flip.kz/catalog?prod=2212672
12197,Вентилятор беспроводной КТ-418,/root/flip/data/category_3/images/Вентилятор_б...,https://www.flip.kz/catalog?prod=4578881
2931,Мужской Шорты Зеленый,/flo_images/6d09a465a006_64a8ebfe.jpg,https://www.flo.com.kz/ru/product/reebok-stren...
16999,Вытяжка Fantasy Light 60,/root/flip/data/category_3/images/Вытяжка_Fant...,https://www.flip.kz/catalog?prod=4623141
6351,Туалетная бумага,/root/flip/data/category_2/images/Туалетная_бу...,https://www.flip.kz/catalog?prod=3333282
4182,"Коллаген гидролизованный, 125 г",/root/flip/data/category_1/images/Коллаген_гид...,https://www.flip.kz/catalog?prod=3197425
6932,"Набор свечей чайных «Long Life», 12 г",/root/flip/data/category_2/images/Набор_свечей...,https://www.flip.kz/catalog?prod=3827320
4098,Маршрутизатор GT-AX11000,/root/flip/data/category_4/images/Маршрутизато...,https://www.flip.kz/catalog?prod=3184386
3527,Морской коллаген 30 стиков,/root/flip/data/category_1/images/Морской_колл...,https://www.flip.kz/catalog?prod=3539535
9057,Мыльница,/root/flip/data/category_2/images/Мыльница_305...,https://www.flip.kz/catalog?prod=2478024
14587,Весы кухонные HT-962-026,/root/flip/data/category_3/images/Весы_кухонны...,https://www.flip.kz/catalog?prod=2230445
1475,"Кроссовки женские на танкетке, черный, 38RU/38EU",/root/flip/data/category_1/images/Кроссовки_же...,https://www.flip.kz/catalog?prod=3152899

In [39]:
list(all_products_combined_ext["product_url"].sample(20))

['https://www.flip.kz/catalog?prod=4083441',
 'https://www.flip.kz/catalog?prod=4168458',
 'https://www.flip.kz/catalog?prod=2784109',
 'https://www.flip.kz/catalog?prod=4158835',
 'https://www.flip.kz/catalog?prod=4869149',
 'https://www.flip.kz/catalog?prod=1643060',
 'https://www.flip.kz/catalog?prod=2913669',
 'https://www.flo.com.kz/ru/product/reebok-reebok-basketball-heat-wa-black-man-449-102047863',
 'https://www.flip.kz/catalog?prod=3133884',
 'https://www.flip.kz/catalog?prod=2709044',
 'https://www.flip.kz/catalog?prod=2586208',
 'https://www.flip.kz/catalog?prod=3537285',
 'https://www.flip.kz/catalog?prod=4228328',
 'https://www.flip.kz/catalog?prod=2346651',
 'https://www.flip.kz/catalog?prod=4107274',
 'https://www.flip.kz/catalog?prod=3705029',
 'https://www.flip.kz/catalog?prod=2554952',
 'https://www.flip.kz/catalog?prod=4884579',
 'https://www.flip.kz/catalog?prod=4254723',
 'https://www.flip.kz/catalog?prod=4664568']

In [54]:
all_products_combined_ext.to_csv(r"C:\Users\User\Downloads\flip_data_vlm\flip_data_vlm\all_products_combined_ext.csv")